version: '3'
services:
  jenkins:
    build: .
    image: custom-jenkins
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50000:50000
    container_name: my-jenkins-3

    volumes:
      - ./jenkins-container-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/external